### ISSUE TITLE
선/후 뉴런 클릭시 weight 값 +1 올리기

### ISSUE THREAD

**Issue by cycorld** [cycorld/brainwiki#10]
- weight : default -> 1
- .prev 와 .next 호출 시 weight 내림차순으로 리턴

**Comment by seobew** [comment]
- synapse에 member로 action하나 추가해서 시냅스를 이용하여 다음 뉴런으로 간 경우, 그 뉴런의 weight값을 올려준다. (참고 : http://guides.rubyonrails.org/routing.html)
